### ISSUE TITLE
Benchmark with Python, Documentation, and License Inquiry

### ISSUE THREAD

**Issue by lewisddffse11** [RVC-Project/obs-rvc#2]
I believe that adding a Python benchmark would be very useful, as one of the main benefits of using Rust is its speed.

Additionally, it would be helpful to include some documentation on how to run the code. While users can figure it out on their own, clear documentation would be greatly appreciated and improve the overall user experience.

Lastly, could you please clarify the license for the code? Is it under the MIT license or another one?

**Comment by wfjsw** [comment]
> I believe that adding a Python benchmark would be very useful, as one of the main benefits of using Rust is its speed.

I might do that after feature parity is achieved and TensorRT is fixed. For a brief view, I don't see much difference in inference time with CUDAExecutionProvider compared to the Python side.

> Additionally, it would be helpful to include some documentation on how to run the code. While users can figure it out on their own, clear documentation would be greatly appreciated and improve the overall user experience.

For the prerelease, extract the zip to `C:\ProgramData\obs-studio\plugins\obsrvc`. There is still a considerable amount of work needs to be done before I can give clear instructions.

> Lastly, could you please clarify the license for the code? Is it under the MIT license or another one?
Since OBS code is incorporated I believe I have to do GPL-3.0. I planned to extract the RVC part and license it under MIT though.
